// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/banner": {
    params: {};
  };
  "/question/:id/answer": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/banner" | "/question/:id/answer";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/banner.tsx": {
    id: "routes/banner";
    page: "/banner";
  };
  "routes/question.$id.answer.ts": {
    id: "routes/question.$id.answer";
    page: "/question/:id/answer";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/banner": typeof import("./app/routes/banner.tsx");
  "routes/question.$id.answer": typeof import("./app/routes/question.$id.answer.ts");
};