/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as QuestionIndexRouteImport } from './routes/question/index'
import { Route as AnswerIndexRouteImport } from './routes/answer/index'
import { Route as QuestionWriteRouteImport } from './routes/question/write'
import { Route as QuestionConfirmRouteImport } from './routes/question/confirm'
import { Route as AnswerMemoRouteImport } from './routes/answer/memo'
import { Route as UserAuthRegisterRouteImport } from './routes/user/auth/register'
import { Route as UserAuthLoginRouteImport } from './routes/user/auth/login'
import { Route as UserKakaoBridgeRegisterRouteImport } from './routes/user/kakao/bridge/register'
import { Route as UserKakaoBridgeLoginRouteImport } from './routes/user/kakao/bridge/login'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionIndexRoute = QuestionIndexRouteImport.update({
  id: '/question/',
  path: '/question/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswerIndexRoute = AnswerIndexRouteImport.update({
  id: '/answer/',
  path: '/answer/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionWriteRoute = QuestionWriteRouteImport.update({
  id: '/question/write',
  path: '/question/write',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionConfirmRoute = QuestionConfirmRouteImport.update({
  id: '/question/confirm',
  path: '/question/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswerMemoRoute = AnswerMemoRouteImport.update({
  id: '/answer/memo',
  path: '/answer/memo',
  getParentRoute: () => rootRouteImport,
} as any)
const UserAuthRegisterRoute = UserAuthRegisterRouteImport.update({
  id: '/user/auth/register',
  path: '/user/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const UserAuthLoginRoute = UserAuthLoginRouteImport.update({
  id: '/user/auth/login',
  path: '/user/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UserKakaoBridgeRegisterRoute = UserKakaoBridgeRegisterRouteImport.update({
  id: '/user/kakao/bridge/register',
  path: '/user/kakao/bridge/register',
  getParentRoute: () => rootRouteImport,
} as any)
const UserKakaoBridgeLoginRoute = UserKakaoBridgeLoginRouteImport.update({
  id: '/user/kakao/bridge/login',
  path: '/user/kakao/bridge/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/answer/memo': typeof AnswerMemoRoute
  '/question/confirm': typeof QuestionConfirmRoute
  '/question/write': typeof QuestionWriteRoute
  '/answer/': typeof AnswerIndexRoute
  '/question/': typeof QuestionIndexRoute
  '/user/': typeof UserIndexRoute
  '/user/auth/login': typeof UserAuthLoginRoute
  '/user/auth/register': typeof UserAuthRegisterRoute
  '/user/kakao/bridge/login': typeof UserKakaoBridgeLoginRoute
  '/user/kakao/bridge/register': typeof UserKakaoBridgeRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/answer/memo': typeof AnswerMemoRoute
  '/question/confirm': typeof QuestionConfirmRoute
  '/question/write': typeof QuestionWriteRoute
  '/answer': typeof AnswerIndexRoute
  '/question': typeof QuestionIndexRoute
  '/user': typeof UserIndexRoute
  '/user/auth/login': typeof UserAuthLoginRoute
  '/user/auth/register': typeof UserAuthRegisterRoute
  '/user/kakao/bridge/login': typeof UserKakaoBridgeLoginRoute
  '/user/kakao/bridge/register': typeof UserKakaoBridgeRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/answer/memo': typeof AnswerMemoRoute
  '/question/confirm': typeof QuestionConfirmRoute
  '/question/write': typeof QuestionWriteRoute
  '/answer/': typeof AnswerIndexRoute
  '/question/': typeof QuestionIndexRoute
  '/user/': typeof UserIndexRoute
  '/user/auth/login': typeof UserAuthLoginRoute
  '/user/auth/register': typeof UserAuthRegisterRoute
  '/user/kakao/bridge/login': typeof UserKakaoBridgeLoginRoute
  '/user/kakao/bridge/register': typeof UserKakaoBridgeRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/answer/memo'
    | '/question/confirm'
    | '/question/write'
    | '/answer/'
    | '/question/'
    | '/user/'
    | '/user/auth/login'
    | '/user/auth/register'
    | '/user/kakao/bridge/login'
    | '/user/kakao/bridge/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/answer/memo'
    | '/question/confirm'
    | '/question/write'
    | '/answer'
    | '/question'
    | '/user'
    | '/user/auth/login'
    | '/user/auth/register'
    | '/user/kakao/bridge/login'
    | '/user/kakao/bridge/register'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/answer/memo'
    | '/question/confirm'
    | '/question/write'
    | '/answer/'
    | '/question/'
    | '/user/'
    | '/user/auth/login'
    | '/user/auth/register'
    | '/user/kakao/bridge/login'
    | '/user/kakao/bridge/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  AnswerMemoRoute: typeof AnswerMemoRoute
  QuestionConfirmRoute: typeof QuestionConfirmRoute
  QuestionWriteRoute: typeof QuestionWriteRoute
  AnswerIndexRoute: typeof AnswerIndexRoute
  QuestionIndexRoute: typeof QuestionIndexRoute
  UserIndexRoute: typeof UserIndexRoute
  UserAuthLoginRoute: typeof UserAuthLoginRoute
  UserAuthRegisterRoute: typeof UserAuthRegisterRoute
  UserKakaoBridgeLoginRoute: typeof UserKakaoBridgeLoginRoute
  UserKakaoBridgeRegisterRoute: typeof UserKakaoBridgeRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question/': {
      id: '/question/'
      path: '/question'
      fullPath: '/question/'
      preLoaderRoute: typeof QuestionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answer/': {
      id: '/answer/'
      path: '/answer'
      fullPath: '/answer/'
      preLoaderRoute: typeof AnswerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question/write': {
      id: '/question/write'
      path: '/question/write'
      fullPath: '/question/write'
      preLoaderRoute: typeof QuestionWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question/confirm': {
      id: '/question/confirm'
      path: '/question/confirm'
      fullPath: '/question/confirm'
      preLoaderRoute: typeof QuestionConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answer/memo': {
      id: '/answer/memo'
      path: '/answer/memo'
      fullPath: '/answer/memo'
      preLoaderRoute: typeof AnswerMemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/auth/register': {
      id: '/user/auth/register'
      path: '/user/auth/register'
      fullPath: '/user/auth/register'
      preLoaderRoute: typeof UserAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/auth/login': {
      id: '/user/auth/login'
      path: '/user/auth/login'
      fullPath: '/user/auth/login'
      preLoaderRoute: typeof UserAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/kakao/bridge/register': {
      id: '/user/kakao/bridge/register'
      path: '/user/kakao/bridge/register'
      fullPath: '/user/kakao/bridge/register'
      preLoaderRoute: typeof UserKakaoBridgeRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/kakao/bridge/login': {
      id: '/user/kakao/bridge/login'
      path: '/user/kakao/bridge/login'
      fullPath: '/user/kakao/bridge/login'
      preLoaderRoute: typeof UserKakaoBridgeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  AnswerMemoRoute: AnswerMemoRoute,
  QuestionConfirmRoute: QuestionConfirmRoute,
  QuestionWriteRoute: QuestionWriteRoute,
  AnswerIndexRoute: AnswerIndexRoute,
  QuestionIndexRoute: QuestionIndexRoute,
  UserIndexRoute: UserIndexRoute,
  UserAuthLoginRoute: UserAuthLoginRoute,
  UserAuthRegisterRoute: UserAuthRegisterRoute,
  UserKakaoBridgeLoginRoute: UserKakaoBridgeLoginRoute,
  UserKakaoBridgeRegisterRoute: UserKakaoBridgeRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
